
server:
  port: 8888
  error:
    path: "/error"
spring:
  application:
    name: Spring Boot Devbox
    admin:
      enabled: true
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://172.17.0.3:5432/buildings
    username: dev
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      file-size-threshold: 2KB
      max-request-size: 215MB
  task:
    execution:
      pool:
        max-size: 20
file:
  upload-dir: "/home/andrii/prog/spring/spring-boot-features-test/uploads"
cat:
  name: Murzik
  age: 6
management:
  info:
    git:
      mode: full
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: health
### LOGGING - https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging
logging:
  file:
    name: "logs/app.log"
  logback:
    rollingpolicy:
      max-file-size: "20MB"
      max-history: 10   # 10 days
#      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz)"
  level:
    root: "info"
    org.springframework.web: "info"
    org.hibernate: "error"
info:
  app:
    java:
      source: 21

---
spring:
  config:
    activate:
      on-profile: cloud