spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      file-size-threshold: 2KB
      max-request-size: 215MB
file:
  upload-dir: E:/Programming/java/files
cat:
  name: Murzik
  age: 6